#!/bin/bash
set -eux

echo "AUTH_TYPE=${AUTH_TYPE}"
admin_user="${AUTH_ADMIN_USER}"
admin_password="${AUTH_ADMIN_PASSWORD}"

while ! fabmanager list-users --app superset 2>/dev/null | grep -q username:${admin_user}; do
    fabmanager create-admin --app superset --username ${admin_user} --password ${admin_password} --firstname '' --lastname '' --email ''
    echo 'Created Superset \"admin\" user'
done

if [[ ! -f /opt/superset/superset-initialized ]]; then
    # Initialize the database
    superset db upgrade

    if [[ ${SUPERSET_LOAD_EXAMPLES:-} = 'yes' ]]; then
        # Load some data to play with
        superset load_examples
    fi

    # Create default roles and permissions
    SUPERSET_UPDATE_PERMS=1 superset init
    touch /opt/superset/superset-initialized
fi


if [ "${#}" -ne 0 ]; then
    exec "${@}"
else
    gunicorn \
        --bind  "0.0.0.0:${SUPERSET_PORT}" \
        --access-logfile '-' \
        --error-logfile '-' \
        --workers 1 \
        --worker-class gthread \
        --threads 20 \
        --timeout 60 \
        --limit-request-line 0 \
        --limit-request-field_size 0 \
        "superset:app"
fi
